### ISSUE TITLE
Test PDAN on demo video to detect spatial temporal actions

### ISSUE THREAD

**Issue by arvindchandel** [dairui01/PDAN#1]
Hi Rui,
I just gone through PDAN today, not complete paper some part of it. It looks promising so if i have to test it on any video, can you provide some demo_video script with clear instruction to test it. 
Thanks in advance.

**Comment by dairui01** [comment]
PDAN is a temporal model to process sequential data. Following this repository, you can train/evaluate this model on Charades or Multithumos data as mentioned in the paper. As the fine-grained action varying largely from dataset to dataset, and there is no general large dataset for pretraining. Thus, it is better to train and test on the same dataset. If you want to train/evaluate other videos, you can change the data loader and the classifier head to your own data.
