### ISSUE TITLE
Toyota Smarthome Untrimmed JSON

### ISSUE THREAD

**Issue by dvidgar** [dairui01/PDAN#5]
Hi! 
Could you share the JSON you generated for the TSU dataset? I'm trying to reproduce the numbers of your paper.
Thanks!

**Comment by dairui01** [comment]
You can find the JSON we used in PDAN here: https://github.com/dairui01/TSU_evaluation/tree/main/Frame_map
As mentioned in the Readme of the dataset, the annotation is refined once after we submitted PDAN. Thus, the JSON can have a slight difference from the provided TSU annotation (CSV format).
