### ISSUE TITLE
features

### ISSUE THREAD

**Issue by mokiki1** [dairui01/PDAN#7]
Thank you for your work.
Can you share the extracted I3D features

**Comment by dairui01** [comment]
It needs a large space to store those Charades features on the cloud drive. 
Currently, I didn't have that much space. As the I3D feature is extracted directly following the repo I provided in README, therefore I invite you to extract it on your own.

If you are not able to extract the feature but still want to play with PDAN. As far as I know, the Toyota Smarthome (TSU) dataset will release the I3D features very soon on their website. You can try PDAN with that dataset. I will release my pretrained model for TSU as well.

**Comment by mokiki1** [comment]
> It needs a large space to store those Charades features on the cloud drive. Currently, I didn't have that much space. As the I3D feature is extracted directly following the repo I provided in README, therefore I invite you to extract it on your own.
> 
> If you are not able to extract the feature but still want to play with PDAN. As far as I know, the Toyota Smarthome (TSU) dataset will release the I3D features very soon on their website. You can try PDAN with that dataset. I will release my pretrained model for TSU as well.

Ok,I would appreciate it if you could share pretrained model for TSU.

**Comment by dairui01** [comment]
The TSU feature you can find on the [website](https://project.inria.fr/toyotasmarthome/)
The PDAN code with its pre-trained weights you can find in this [repo](https://github.com/dairui01/Toyota_Smarthome/tree/main/pipline)
